### ISSUE TITLE
FHEM mirror repository does not sync anymore

### ISSUE THREAD

**Issue by 1100101** [mhop/fhem-mirror#59]
This mirror repository of FHEM's official SVN repo appears to not sync anymore with the official repository.
The last commit here is from mid August, but the FHM SVN repo has seen many commits since then.

Could you please fix any issues so that the Github mirror is up-to-date again?

Thanks!

**Comment by mhop** [comment]
fixed

**Comment by 1100101** [comment]
@mhop It seems the mirroring is again broken. Last update here is from March 23rd, which is over a month ago.
